[package]
name = "LaunchB0xx_FungibleTokenMinter"
version = "1.0.0"
authors = []

[addresses]
admin = '_'
initial_creator_addr = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework"}

[dev-dependencies]
